Fix/calender period highlight
bcc-code/brunstadtv pull request #309
Opened 2023-04-11 12:42 UTC by starkris51

2023-04-12 07:30 UTC, KillerX commented on backend/.vscode/launch.json
> +            "name": "Launch Package",
This probably needs a more sane name? API for example.

2023-04-12 07:30 UTC, KillerX commented on web/src/pages/calendar/Calendar.vue
It is somewhat hard to understand what was actually changed here due to the whitespace changes.

2023-04-18 08:17 UTC, andreasgan commented on web/src/pages/calendar/Calendar.vue
> -const startEvent = (day: Date) => {
Yes, this was a comment from me. It made more sense, because you are passing in a date, and the function is finding the `day` (int) from the date.

2023-04-18 08:18 UTC, andreasgan commented on backend/.vscode/launch.json
> +            "name": "Launch Package",
```suggestion
            "name": "api",
```

2023-04-18 08:21 UTC, andreasgan commented on web/src/pages/calendar/Calendar.vue
The HTML part looks like 100% whitespace changes.. idk, it looked like he had correct formatters set up..

2023-04-18 08:21 UTC, andreasgan commented on web/src/pages/calendar/Calendar.vue
The js part is basically changing a string comparison to an int comparison, so that it works.
`if (start < dayString && end > dayString)`

2023-04-18 08:22 UTC, andreasgan requested changes

2023-04-18 08:22 UTC, andreasgan commented on web/src/pages/calendar/Calendar.vue
> +        /*const start = isoDateString(new Date(e.start))
My only comment is that you should remove the // and /* */ comments you added @starkris51

2023-04-18 08:26 UTC, fredrikved commented on web/src/pages/calendar/Calendar.vue
`pnpm prettier` fixes the whitespace diff. 
might need to add that extension if something else formats on save.

2023-04-25 07:35 UTC, andreasgan approved these changes

2023-04-25 07:35 UTC, merged